### ISSUE TITLE
Gust wind speed is off the chart in some undetermined situation

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#67] opened 2022-05-13 05:42 UTC
## WeatherXM Related Element
- Android Application

## **Describe the bug**
The wind speeds chart should show 2 points for each time on the x-axis. In a circumstance I captured of 1 time value (in the first hour of the day), the gust speed is not displayed on the chart, and seems above the upper range of the y-axis

### **How To Reproduce**
1. Recreate windspeed data for the first 26 minutes of my station on 13 May (UTC -5) of 3.2 mph wind speed and 4.3 mph gust speed. Make sure and have settings set to mph.
2. Click on historical charts
3. Notice the chart for windspeed, and notice that the gust is not on the chart. Click on the data point to see the actual value for windspeed and gust speed in the blue popup box. 

### **Expected behavior**
Both the windspeed and gust speed should be within the y-axis range, and should appear on the chart.

### **Screenshots**
![Screenshot_20220513-002636.png](https://user-images.githubusercontent.com/70354350/168218614-8160ea98-37c8-4a63-9aa6-c36addff7dc4.png)
![Screenshot_20220513-002651.png](https://user-images.githubusercontent.com/70354350/168218624-cd95bfd6-71b9-4092-a0b2-066b2d585548.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: moto g7 power
 - OS: android 10
 - Android App Version 3.1.0-3a64cd1

### **Additional context**
In this instance, the issue appeared when units are mph or km/h, but not m/s. I didn't check what happens when knots or Beaufort were chosen.

**Comment by Greg15** [comment] 2022-05-13 13:02
I checked later in the day, and this is the scenario I now see. The first gust data point is still off the chart, but this means the bug isn't limited to when there is only one data point, although it could possibly be related to the specific data of the first data point.
![Screenshot_20220513-075928.png](https://user-images.githubusercontent.com/70354350/168289032-1dfe51d4-c5b9-417e-9cc7-bd93f1813e3b.png)

**Comment by PavlosTze** [comment] 2022-05-13 21:41
I fixed the initial one bug regarding the only one datapoint.

Regarding the other:
If that happens again can you please give me the numbers of the highest and lowest data point (both wind speed and wind gust)? I struggle to reproduce this.

**Comment by Greg15** [comment] 2022-05-14 07:25
Here are the actual data values of the highest and lowest values for that actual graph with 8 data points.

Highest gust was at midnight and 1am - with a value of 4.1mph.
Lowest gust was at 4am with a value of 1.8mph

Highest wind speed was at 1am with a value of 3.0mph.
Lowest wind speed was at 4am with a value of 1.3mph

You can see the graph displays correctly later in the day when additional data points set a new high value.
![Screenshot_20220514-021733.png](https://user-images.githubusercontent.com/70354350/168415550-21b2cbcb-1422-48b8-bdf9-af69c4a52b12.png)
![Screenshot_20220514-021910.png](https://user-images.githubusercontent.com/70354350/168415562-2ba088a6-4bb6-49bb-adbf-a9e32032bd3c.png)
![Screenshot_20220514-021709.png](https://user-images.githubusercontent.com/70354350/168415570-2f0784b5-bef5-4858-8c45-4b7ac18a76bd.png)

**Comment by PavlosTze** [comment] 2022-05-16 10:30
@Greg15 Getting the highest and lowest values didn't do the trick. I still cannot reproduce it even in by using your phone configuration.

Can you please send me all the values of `wind speed` and `wind gust` from 00:00am to 07:00am so I can give it another try?

**Comment by Greg15** [comment] 2022-05-17 15:13
@PavlosTze The following values are in mph:
Time, Wind, Gust
12am, 2.9, 4.1
1am, 3.0, 4.1
2am, 2.6, 3.5
3am, 2.4, 3.2
4am, 1.3, 1.8
5am, 1.5, 2.2
6am, 1.5, 2.3
7am, 1.7, 2.3

**Comment by PavlosTze** [comment] 2022-05-17 20:19
I think issue identified and fixed internally @Greg15 . Thank you!

**Comment by PavlosTze** [comment] 2022-05-24 07:56
We just released a new beta version which addresses this issue. Therefore I am closing this. If it's not fixed please let me know!

Thank you! :)

**Closed by PavlosTze** 2022-05-24 07:56 UTC
Labels: bug, android app
