### ISSUE TITLE
iOS not converting Daily Precip Total from mm to inches

### ISSUE THREAD

**Issue by atmovantage** [WeatherXM/issue-tracker#190] opened 2023-07-16 13:36 UTC
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- iOS Application

## **Describe the bug**

In the iOS app (v1.6.1) the new values for total Daily Precip show the value for millimeters even though my settings are configured to use inches.

### **How To Reproduce**
1. Go to "iOS app" (make sure profile is set to use inches)
2. Click on 'Historical Data'
3. Scroll down to 'Precipitation' charts
4. Note the values for Daily Precip
5. Go back to profile settings and change to mm
6. Return to historical Precip chart and note the values for Daily are the same, but now labeled "mm"

### **Expected behavior**

The Daily Precip values in the Historical chart should be converted from mm to inches when my profile is configured to use "inches"

### **Screenshots**
![image](https://github.com/WeatherXM/issue-tracker/assets/13420350/9ae2fb8e-4bb9-48c4-b27b-77bc3377be4b)
![image](https://github.com/WeatherXM/issue-tracker/assets/13420350/7ebf0e5c-f876-40ff-ac70-5791ec4eeef2)

**Comment by pantelisss** [comment] 2023-09-04 13:03
The issue is fixed in the latest version 1.7.0. Thanks for the report!

**Closed by pantelisss** 2023-09-04 13:03 UTC
Labels: bug, Acknowledged, iOS
