### ISSUE TITLE
[Pressure Graph]

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#15] opened 2022-02-26 10:23 UTC
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Android Application

## **Describe the bug**
When seeing historic data in pressure graph the values don't change and the y-axis don't have name 

### **How To Reproduce**
1. Go to station in the app
2. Click on historical charts
3. Scroll down to pressure and press different parts of the graph.
4. All values are similar and no y-axis name

### **Expected behavior**
Since there is fluctuation in the graph I would expect different values.

### **Screenshots**
![Screenshot_2022-02-26-12-13-41-728_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/155839541-09cf5df7-311c-457b-91ff-0c43f62d5c4a.jpg)
![Screenshot_2022-02-26-12-13-45-191_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/155839548-38fc81f2-74c6-4806-a89f-a4b33325b08f.jpg)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**

 - Android App Version 3.0.3-3f653e9

**Comment by RevNotDev** [comment] 2022-02-26 13:22
I'm not seeing this issue. The y-axis shows for me and values change as expected.
Same android app version, latest beta.
![image](https://user-images.githubusercontent.com/46647866/155844869-6142d932-5c58-4d72-bce5-e8e4d1a29152.png)

**Comment by EmperorDRT1** [comment] 2022-02-26 18:26
### There are multiple issues going on here:

1. Both Katsoul and Rev are viewing pressure readings in units of hPa but the actual values are in units of inHg. The lowest recorded air pressure on Earth was 870 hPa. For comparison, If the air pressure readings (in hPa) seen by Katsoul and Rev were to be true, they would be living in an environment with an air pressure lower than Jupiter. 

2. It's possible that Katsoul's air pressure graph's fluctuations are correct as it is displaying the actual values while the data popup is rounding the values (making it appear as though all values are the same with no fluctuation while in actuality they differ by multiple decimal places). This issue might be the reason why Katsoul is unable to view the y-axis. 

3. I am able to reproduce the no y-axis issue for air pressure when I switch my units from hPa to inHg. I have no issues displaying the graph, data popup, and y-axis when my units are in hPa. 

#### I have attached an image of my graph when in units of hPa (correct) and when in units of inHg (bug).

![SmartSelect_20220226-121205_WeatherXM](https://user-images.githubusercontent.com/44149620/155854431-94a8fbbc-e4f9-4e43-b8c6-7d753b0b0183.jpg)
![SmartSelect_20220226-121349_WeatherXM](https://user-images.githubusercontent.com/44149620/155854469-ad2da787-8b02-4680-b4f3-8f068ce22649.jpg)

Android App Version 3.0.3-3f653e9

**Comment by RevNotDev** [comment] 2022-02-26 20:06
Well spotted DRT! I suppose it helps when you actually understand the pressure measurement values. I've never dealt with pressure measurements in either units so your explanation really helps, thanks.

**Comment by kkatsoulak** [comment] 2022-02-27 06:08
After DRT comment I went to change the settings and it looks like the problem with the y-axis is caused by the new beta version were all settings for displayed units are gone. If you select them then the y-axis is displayed. I had the same problem with the wind (but didn't noticed it until now)

Here is a screenshot of my settings.
In previous version I had them selected

![Screenshot_2022-02-27-08-04-13-856_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/155870524-adaf8266-a5ee-4d40-bdef-57e75de89edc.jpg)

**Comment by PavlosTze** [comment] 2022-02-28 11:58
@RevNotDev @kkatsoulak If you re-set the settings values, does this issue still occurs?

**Comment by kkatsoulak** [comment] 2022-02-28 13:53
If you reset the values and select the appearing method then the problem is resolved. 

But the one that DRT is mentioning, about the values, is another thing.

**Comment by PavlosTze** [comment] 2022-02-28 14:19
Thank you, will fix it!

**Comment by PavlosTze** [comment] 2022-03-03 14:42
Fixed on the latest beta version.

**Closed** 2022-03-03 14:43 UTC
Labels: bug, android app
