### ISSUE TITLE
7 Day Forecast Visual Improvement - Move umbrella icon over

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#17] opened 2022-02-27 20:42 UTC
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- Android Application

### **Is your feature request related to a problem? Please describe.**
Visual improvement

### **Describe the solution you'd like**
The umbrella icon on the 7 day forecast is right next to every weather icon, whether full sun or rain. I assume this umbrella icon is to show the percentage to the right-hand side of it is the percentage chance of rain. I think it would make more sense to have the umbrella icon right next to the percentage chance of rain, rather than right next to the weather icon for the day.

### **Additional context**
Before
![Screenshot 2022-02-27 200947](https://user-images.githubusercontent.com/46647866/155899045-2dd1e5a6-84bf-4123-afa6-bea4fc5c8d01.jpg)
After
![Screenshot 2022-02-27 200948](https://user-images.githubusercontent.com/46647866/155899047-0e639e1e-15c1-4727-8d17-7c7a87b2818c.jpg)

**Comment by EmperorDRT1** [comment] 2022-02-28 06:50
That's very interesting! It appears as though this issue is only noticeable on wider aspect ratios, as I was unable to reproduce the degree of spacing on my mobile device. The umbrellas seem to be aligned with the weather icons rather than the precipitation percentages in the code (or the default alignment position places it next to the first element). 

![SmartSelect_20220228-004501_WeatherXM](https://user-images.githubusercontent.com/44149620/155936777-8608d1b6-2d54-4f91-92f2-6aae34177082.jpg)
Android App Version 3.0.3-3f653e9

**Comment by PavlosTze** [comment] 2022-02-28 15:03
Issue identified. Thank you.

**Comment by eeVoskos** [comment] 2022-03-01 10:01
> That's very interesting! It appears as though this issue is only noticeable on wider aspect ratios, as I was unable to reproduce the degree of spacing on my mobile device. The umbrellas seem to be aligned with the weather icons rather than the precipitation percentages in the code (or the default alignment position places it next to the first element).
> 
> ![SmartSelect_20220228-004501_WeatherXM](https://user-images.githubusercontent.com/44149620/155936777-8608d1b6-2d54-4f91-92f2-6aae34177082.jpg) Android App Version 3.0.3-3f653e9

We really need to add an "official" dark theme at some point, I love it!

**Comment by PavlosTze** [comment] 2022-03-03 14:42
Fixed on the latest beta version.

**Closed by PavlosTze** 2022-03-03 14:42 UTC
Labels: suggestion, android app
